services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cloudStorageDb'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
